# Jekyll Configuration
title: "Magnify Development Blog"
description: "macOS Screen Annotation Tool Development Journey - ZoomIt Alternative App Development Project"
baseurl: "/Magnify"
url: "https://jayleekr.github.io"

# Author Information
author:
  name: "Jay Lee"
  email: "jay@example.com"
  github: "jayleekr"

# Site Settings
timezone: Asia/Seoul
lang: en

# Jekyll Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Collections Settings
collections:
  milestones:
    output: true
    permalink: /:collection/:name/

# Defaults Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jay Lee"
  - scope:
      path: ""
      type: "milestones"
    values:
      layout: "milestone"

# Project-Specific Settings
project:
  name: "Magnify"
  description: "macOS Screen Annotation Tool"
  version: "1.0.0"
  github_repo: "https://github.com/jayleekr/Magnify"
  app_store_url: "#"
  bundle_id: "com.jayleekr.magnify"
  start_date: "2025-05-30"
  
# Progress Status (As of May 30, 2025)
progress:
  total_milestones: 5
  total_checkpoints: 20
  current_milestone: 1
  current_checkpoint: 1
  completion_percentage: 5

# Development Schedule (Starting May 30, 2025)
schedule:
  milestone_1:
    start: "2025-05-30"
    end: "2025-06-13"
    title: "Core Infrastructure"
  milestone_2:
    start: "2025-06-14"
    end: "2025-06-27"
    title: "Zoom & Annotation Core"
  milestone_3:
    start: "2025-06-28"
    end: "2025-07-11"
    title: "Advanced Features"
  milestone_4:
    start: "2025-07-12"
    end: "2025-07-25"
    title: "Polish & Testing"
  milestone_5:
    start: "2025-07-26"
    end: "2025-08-01"
    title: "App Store Launch" 